baseURL = 'https://blog.777000.best/'
languageCode = 'en-us'
title = 'Sevono'
theme = 'PaperMod'

[menus]
[[menus.main]]
name = 'home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'feed'
url = '/index.xml'
weight = 40

# [[menus.main]]
#   name = 'search'
#   url = '/search'
#   weight = 50

# [module]
#   [module.hugoVersion]
#     extended = false
#     min = '0.146.0'

paginate = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Sevono"
description = "My Personal Blog, pourover coffee, photography, AI, technology, and more"
keywords = ["Blog", "Portfolio"]
author = ""
# author = ["Me", "You"] # 多作者写法
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "January 2, 2006"
defaultTheme = "light"
disableThemeToggle = true

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
# disableHLJS = true
# disableFingerprinting = true
favicon = "/icons/hubot.svg"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Sevono"
icon = "/icons/hubot.svg"
iconHeight = 27

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"
[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

# [params.homeInfoParams]
#   Title = "Hi there "
#   Content = "Welcome to my blog"

# [[params.socialIcons]]
#   name = "x"
#   url = "https://x.com/"
# [[params.socialIcons]]
#   name = "stackoverflow"
#   url = "https://stackoverflow.com"
# [[params.socialIcons]]
#   name = "github"
#   url = "https://github.com/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"
[params.analytics.bing]
SiteVerificationTag = "XYZabc"
[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

# [params.editPost]
#   URL = "https://github.com/ywz/hugo_blog/content"
#   Text = "Suggest Changes"
#   appendFilePath = false

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

pygmentsUseClasses = true

[markup]
[markup.highlight]
noClasses = false
tabWidth = 2
# anchorLineNos = true
# codeFences = true
# guessSyntax = true
# lineNos = true
# style = "monokai"

