baseURL = 'https://blog.777000.best/'
languageCode = 'en-us'
title = 'Sevono'
theme = 'PaperMod'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
    
  [[menus.main]]
    name = 'RSS'
    url = '/index.xml'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[markup]
  [markup.highlight]
      noClasses=false
      tabWidth =2